from infermation.dtypes import dtypes

teradata_dtypes_map = {
        dtypes.integer: 'INTEGER',
        dtypes.float: 'FLOAT',
        dtypes.date: 'DATE',
        dtypes.datetime: 'TIMESTAMP',
        dtypes.invalid: 'VARCHAR(1000)'
}


# SELECT
# DATABASENAME, TABLENAME, COLUMNNAME, TRIM(COLUMNTYPE)||'('||TRIM(COLUMNNUM)||')'
# FROM (
#   SELECT DATABASENAME, TABLENAME, COLUMNNAME,
#   CASE
#     WHEN COLUMNTYPE='CF' THEN 'CHAR'
#     WHEN COLUMNTYPE='CV' THEN 'VARCHAR'
#     WHEN COLUMNTYPE='D'  THEN 'DECIMAL'
#     WHEN COLUMNTYPE='TS' THEN 'TIMESTAMP'
#     WHEN COLUMNTYPE='I'  THEN 'INTEGER'
#     WHEN COLUMNTYPE='I2' THEN 'SMALLINT'
#     WHEN COLUMNTYPE='DA' THEN 'DATE'
#   END AS COLUMNTYPE,
#   CASE
#     WHEN COLUMNTYPE='CF' THEN COLUMNLENGTH
#     WHEN COLUMNTYPE='CV' THEN COLUMNLENGTH
#     WHEN COLUMNTYPE='D'  THEN (DECIMALTOTALDIGITS||','||DECIMALFRACTIONALDIGITS)
#     WHEN COLUMNTYPE='TS' THEN COLUMNLENGTH
#     WHEN COLUMNTYPE='I'  THEN DECIMALTOTALDIGITS
#     WHEN COLUMNTYPE='I2' THEN DECIMALTOTALDIGITS
#     WHEN COLUMNTYPE='DA' THEN NULL
#   END AS COLUMNNUM
#   FROM DBC.COLUMNS
#   WHERE DATABASENAME='TDDB02'
# ) TBL